dist: trusty

addons:
  chrome: stable

language: node_js

node_js:
  - '8'

cache:
  yarn: true

bundler_args: --retry 5

install:
  - travis_retry yarn install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - ng -v

script:
  - yarn lint
  - yarn build:ssr
  - yarn e2e
  - yarn test:cover

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js